// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/core/user/proto/user.proto

package proto

import (
	context "context"
	fmt "fmt"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e516e2369a0dce2d, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateResponse struct {
	Error                int32    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e516e2369a0dce2d, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
}

func init() { proto.RegisterFile("app/core/user/proto/user.proto", fileDescriptor_e516e2369a0dce2d) }

var fileDescriptor_e516e2369a0dce2d = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x35, 0x7a, 0xc9, 0x99, 0xf1, 0xa3, 0x18, 0x4e, 0x0c, 0x27, 0x88, 0x97, 0xca, 0x2a, 0x01,
	0x2d, 0x2c, 0x85, 0xb3, 0xb2, 0x39, 0x8e, 0x80, 0x8d, 0xcd, 0xb1, 0x67, 0x06, 0x0d, 0x98, 0xec,
	0x3a, 0x93, 0x20, 0xf6, 0xfe, 0x70, 0xd9, 0xd9, 0x8b, 0xa0, 0xd5, 0xce, 0x7b, 0x6f, 0xdf, 0xcc,
	0x9b, 0x81, 0x4b, 0xe3, 0x5c, 0xf9, 0x62, 0x99, 0xca, 0x41, 0x88, 0x4b, 0xc7, 0xb6, 0xb7, 0x5a,
	0x16, 0x5a, 0x62, 0xac, 0x4f, 0xfe, 0x1d, 0xc1, 0xc9, 0x03, 0x93, 0xe9, 0xa9, 0xa2, 0x8f, 0x81,
	0xa4, 0xc7, 0x73, 0x98, 0xfa, 0x6f, 0x9b, 0xa6, 0xce, 0xa2, 0xab, 0xe8, 0x3a, 0xad, 0x12, 0x0f,
	0x1f, 0x6b, 0x9c, 0xc3, 0xa1, 0x33, 0x22, 0x9f, 0x96, 0xeb, 0x6c, 0x5f, 0x95, 0x5f, 0x8c, 0x17,
	0x90, 0xaa, 0xa9, 0x33, 0x2d, 0x65, 0x07, 0x41, 0xf4, 0xc4, 0xca, 0xb4, 0x84, 0x0b, 0x38, 0x76,
	0x6f, 0xb6, 0xa3, 0x4d, 0x37, 0xb4, 0x5b, 0xe2, 0x6c, 0xa2, 0xfa, 0x91, 0x72, 0x2b, 0xa5, 0xf2,
	0x67, 0x38, 0x1d, 0x53, 0x88, 0xb3, 0x9d, 0x10, 0xce, 0x20, 0x26, 0x66, 0xcb, 0x1a, 0x22, 0xae,
	0x02, 0xc0, 0x0c, 0xa6, 0x2d, 0x89, 0x98, 0x57, 0xda, 0x45, 0x18, 0xa1, 0x57, 0x6a, 0xea, 0x4d,
	0xf3, 0x2e, 0xbb, 0xf9, 0x23, 0xbc, 0xb9, 0x87, 0xc9, 0x93, 0x10, 0xe3, 0x1d, 0x24, 0x61, 0x06,
	0xce, 0xc2, 0x0d, 0x8a, 0x3f, 0x8b, 0xcf, 0xcf, 0xfe, 0xb1, 0x21, 0x48, 0xbe, 0xb7, 0x5c, 0x00,
	0x7e, 0x0d, 0x6d, 0x53, 0x18, 0xe7, 0x0a, 0x7f, 0xd1, 0xc2, 0x6f, 0xb6, 0x4c, 0x7d, 0xd3, 0xb5,
	0x77, 0xac, 0xa3, 0x6d, 0xa2, 0xd6, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x59, 0xad,
	0xc4, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.User/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/core/user/proto/user.proto",
}
