#webapiHTTP服务器配置
[HttpServer]
	Addr = "0.0.0.0"
	Port = 2011
	WriteTimeOut = "15s"
	ReadTimeOut = "15s"
	NodeId = 10   #节点ID,用于标识不同服务的ID，两位整数
	TempPwd = "123456"	 #用于临时用户登录验证
	Debug = true

[ENGINE]
	LoadloadIncrease = true  #是否加载增量，在一些演示环境，不加载增量更优化
	LocalStorage = true  	 #引擎数据持久化
	ReLoadEveryDayAtHour = 15 #每天重新加载的时间，这里配置小时序数
	# 如果不重新加载，这里可以设置成0-23之外的数字

[Document]
	AllowDownload = false
	RejectDownloadWarnText = "该系统处于内测阶段，不允许下载"
	ImportDownloadPath = "H:\\out\\download\\"
	DownloadFilePath = "H:\\downloadfile\\"
	DownloadZipPath = "H:\\downloadtempzip\\"

[SystemCfg]
	MaxSmsTotalEveryDay = 10000  #每天平台最大短信数量，用于防止恶意用户乱获取短信验证码
	MaxSmsEveryIpEveryDay = 300  #每个IP每天最大短信数量，用于防止恶意用户获取短信验证码

#数据库配置
[MsSqlDb]
	Dsn = "sqlserver://sa:111111@192.168.8.10?database=statute_2020&encrypt=disable"
	MaxOpenConns = 100
	MaxIdleConns = 20
	SqlLogToFile = true
	ErrLogToFile = true

[SMSAPI]
    BaseUrl = "http://120.78.148.90:20192"
    AppId = "webapi_local"
    Secure = "zzyq!@#$%"

[Log]
	#Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
	ConsoleShow  =  true
	ConsoleLevel =  7
	FileWrite   =   false
	FileLevel   =  7
	MultiFileWrite = true
	MultiFileLevel = 7
