package mysqlx

import (
	"context"
	"database/sql"
)

// CURD ...
type CURD interface {
	// Insert ...
	Insert(query string, args ...interface{}) (int64, error)
	// ExecContext ...
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	// Exec ...
	Exec(query string, args ...interface{}) (sql.Result, error)
	// Get ...
	Get(dest interface{}, query string, args ...interface{}) error
	// Delete ...
	Delete(query string, args ...interface{}) error
	// PageSelect ...
	PageSelect(dest interface{}, cloumns, table, where, order string, index, size int, args ...interface{}) (
		total, curIndex, curCount int, err error)
}
