[Program]
    SysName = "erpsys"
    Environment = "debug"
[Server]
    Addr = "0.0.0.0:8888"
    WriteTimeout = "15s"
    ReadTimeout = "15s"
[Media]
    StoragePath = "media"
    MaxFileSize = "32mb" # 32M‬
[DBC]
    Dsn = ""
    DBName = ""
    MaxOpenConns = 10
    MaxIdleConns = 10
    ConnMaxLifetime = "2h" #hour
[Cache]

[Email]

[Pay]
