[HostEnv]
    SysName = "yumi"
    Environment = "dev"

[HTTPServer]
    Addr = "0.0.0.0:8888"
    WriteTimeout = "15s"
    ReadTimeout = "15s"
[DBC]
    DBName = ""
    Dsn = ""
    MaxOpenConns = 10
    MaxIdleConns = 10
    ConnMaxLifetime = "2h"
[Mongodb]

[Cache]

[Log]


# 业务配置
[Email]

[Pay]

[Media]
    StoragePath = "media"
    MultipleFileUploadsMaxSize = "32mb"
    SingleFileUploadsMaxSize = "2mb"
[OnlyOffice]
    ConfigPath = "./office_config.json"
    SiteUrl = "http://localhost/"
    CommandUrl = "coauthoring/CommandService.ashx"
    ConverterUrl =  "ConvertService.ashx"
    TempStorageUrl =  "ResourceService.ashx"
    ApiUrl =  "web-apps/apps/api/documents/api.js"
    PreloaderUrl =  "web-apps/apps/api/documents/cache-scripts.html"
    ExampleUrl =  ""
    ViewedDocs =  [".pdf", ".djvu", ".xps"]
    EditedDocs =  [".docx", ".xlsx", ".csv", ".pptx", ".txt"]
    ConvertedDocs = [".docm", ".doc", ".dotx", ".dotm", ".dot", ".odt", ".fodt", ".ott", ".xlsm", ".xls", ".xltx", ".xltm", ".xlt", ".ods", ".fods", ".ots", ".pptm", ".ppt", ".ppsx", ".ppsm", ".pps", ".potx", ".potm", ".pot", ".odp", ".fodp", ".otp", ".rtf", ".mht", ".html", ".htm", ".epub"]
    StorageFolder =  "files"
    MaxFileSize =  "10mb"
    MobileRegEx =  "android|avantgo|playbook|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od|ad)|iris|kindle|lge |maemo|midp|mmp|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\\/|plucker|pocket|psp|symbian|treo|up\\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino"
    [[Static]]
        Name = "/public"
        Path = "public"
    [Token]
        Enable = false
        UseForRequest = true
        AlgorithmRequest = "HS256"
        AuthorizationHeader = "Authorization"
        AuthorizationHeaderPrefix = "Bearer "
        Secret = "secret"
        ExpiresIn = "5m"