[Server]
    SysName = "erpsys"
    Addr = "0.0.0.0:8888"
    WriteTimeout = 30
    ReadTimeout = 30
    Environment = "debug"
    StoragePath = "media"
    MaxFileSize = 33554432 # 32M‬
[DBC]
    Dsn = ""
    DBName = ""
    MaxOpenConns = 10
    MaxIdleConns = 10
    ConnMaxLifetime = 2 #hour
[Cache]

[Email]

[Pay]
