FROM golang:1.15 AS builder

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /app

COPY . .

# CGO_ENABLED禁用cgo 然后指定OS等，并go build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app .

# 运行阶段指定scratch作为基础镜像
FROM scratch

WORKDIR /app

# 指定运行时环境变量
ENV PORT=80

EXPOSE ${PORT}

ENTRYPOINT ["app"]
